index:
    path: /inicio
    controller: App\Controller\HomeController::index

animales:
    path: /animales/{nombre}/{apellidos}
    controller: App\Controller\HomeController::animales
    defaults: {nombre: 'David', apellidos: 'Garcia'}
    methods: [GET]
    requirements:
      nombre: '[a-zA-Z ]+'
      apellidos: '[a-zA-Z ]+'

redirigir:
    path: /redirigir
    controller: App\Controller\HomeController::redirigir